# Generated by Django 4.2 on 2025-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
