# Generated by Django 4.2 on 2025-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_each',
            field=models.BooleanField(default=True),
        ),
    ]
